### PR TITLE
Fix source_text treating span.lo as byte offset not char index

### LINKED ISSUE #410: Issue with multibyte chars in source_text() computation
It treats `lo` as a byte index, while it is actually a character index:

https://github.com/dtolnay/proc-macro2/blob/7f5533d6cc9ff783d174aec4e3be2caa202b62ca/src/fallback.rs#L367

I expect this test to pass, but it does not:

```rust
#[cfg(span_locations)]
#[test]
fn source_text() {
    let input = "    𓀕 c    ";
    let mut tokens = input
        .parse::<proc_macro2::TokenStream>()
        .unwrap()
        .into_iter();

    let ident1 = tokens.next().unwrap();
    assert_eq!("𓀕", ident1.span().source_text().unwrap());

    let ident2 = tokens.next().unwrap();
    assert_eq!("𓀕", ident2.span().source_text().unwrap());
}
```

Panics with (as character `𓀕` occupies byte 5 and 6)
```
---- source_text stdout ----
thread 'source_text' panicked at 'byte index 6 is not a char boundary; it is inside '𓀕' (bytes 4..8) of `    𓀕 c   `', src/fallback.rs:367:25
```

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #410.

### CODE REVIEW

File: src/fallback.rs [hunk 1]
```diff
@@ -364,7 +364,10 @@ impl FileInfo {
 
     fn source_text(&self, span: Span) -> String {
         let lo = (span.lo - self.span.lo) as usize;
-        let trunc_lo = &self.source_text[lo..];
+        let trunc_lo = match self.source_text.char_indices().nth(lo) {
```
Comment (dtolnay) [inline src/fallback.rs:367]: This makes it _O(n²)_ to compute the source_text of lots of tokens in the same stream, which is probably an important use case. I'll follow up with a separate PR to amortize this.

```rust
for token in token_stream {
    let _ = token.span().source_text();
}
```

Comment (dtolnay) [reply src/fallback.rs:367]: #412
